"""Add experts module tables

Revision ID: c86a6698d1f3
Revises: 9609b426b218
Create Date: 2026-07-12 17:19:23.686580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c86a6698d1f3'
down_revision: Union[str, Sequence[str], None] = '9609b426b218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expert_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=False),
    sa.Column('specialisation', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('consultations_count', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('consultations_count >= 0', name='chk_expert_consultations_count_positive'),
    sa.CheckConstraint('price >= 0', name='chk_expert_price_positive'),
    sa.CheckConstraint('rating >= 0 AND rating <= 5', name='chk_expert_rating_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_expert_profiles_specialisation', 'expert_profiles', ['specialisation'], unique=False)
    op.create_table('consultations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('expert_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('slot', sa.String(length=100), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('review_rating', sa.Integer(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mode IN ('Chat', 'Video')", name='chk_consultation_mode'),
    sa.CheckConstraint("status IN ('Pending', 'Confirmed', 'Completed', 'Cancelled')", name='chk_consultation_status'),
    sa.CheckConstraint('review_rating IS NULL OR (review_rating >= 1 AND review_rating <= 5)', name='chk_consultation_review_rating'),
    sa.ForeignKeyConstraint(['expert_id'], ['expert_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_expert_id'), 'consultations', ['expert_id'], unique=False)
    op.create_index(op.f('ix_consultations_user_id'), 'consultations', ['user_id'], unique=False)
    op.create_index('ix_consultations_user_id_status', 'consultations', ['user_id', 'status'], unique=False)
    op.create_table('consultation_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('consultation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_messages_consultation_id'), 'consultation_messages', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_consultation_messages_sender_id'), 'consultation_messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultation_messages_sender_id'), table_name='consultation_messages')
    op.drop_index(op.f('ix_consultation_messages_consultation_id'), table_name='consultation_messages')
    op.drop_table('consultation_messages')
    op.drop_index('ix_consultations_user_id_status', table_name='consultations')
    op.drop_index(op.f('ix_consultations_user_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_expert_id'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_index('ix_expert_profiles_specialisation', table_name='expert_profiles')
    op.drop_table('expert_profiles')
    # ### end Alembic commands ###
