/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSupportRouteImport } from './routes/_app.support'
import { Route as AppSubscriptionRouteImport } from './routes/_app.subscription'
import { Route as AppSellerRouteImport } from './routes/_app.seller'
import { Route as AppRemindersRouteImport } from './routes/_app.reminders'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCheckoutRouteImport } from './routes/_app.checkout'
import { Route as AppCartRouteImport } from './routes/_app.cart'
import { Route as AppSellerIndexRouteImport } from './routes/_app.seller.index'
import { Route as AppOrdersIndexRouteImport } from './routes/_app.orders.index'
import { Route as AppMarketIndexRouteImport } from './routes/_app.market.index'
import { Route as AppLearnIndexRouteImport } from './routes/_app.learn.index'
import { Route as AppExpertsIndexRouteImport } from './routes/_app.experts.index'
import { Route as AppDetectIndexRouteImport } from './routes/_app.detect.index'
import { Route as AppConsultationsIndexRouteImport } from './routes/_app.consultations.index'
import { Route as AppCommunityIndexRouteImport } from './routes/_app.community.index'
import { Route as AppSellerProductsRouteImport } from './routes/_app.seller.products'
import { Route as AppSellerOrdersRouteImport } from './routes/_app.seller.orders'
import { Route as AppPlantsIdRouteImport } from './routes/_app.plants.$id'
import { Route as AppOrdersIdRouteImport } from './routes/_app.orders.$id'
import { Route as AppLearnSlugRouteImport } from './routes/_app.learn.$slug'
import { Route as AppExpertsIdRouteImport } from './routes/_app.experts.$id'
import { Route as AppDetectHistoryRouteImport } from './routes/_app.detect.history'
import { Route as AppMarketProductIdRouteImport } from './routes/_app.market.product.$id'
import { Route as AppDetectResultIdRouteImport } from './routes/_app.detect.result.$id'
import { Route as AppConsultationsIdChatRouteImport } from './routes/_app.consultations.$id.chat'
import { Route as AppCommunityPostIdRouteImport } from './routes/_app.community.post.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppSellerRoute = AppSellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => AppRoute,
} as any)
const AppRemindersRoute = AppRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppRoute,
} as any)
const AppCartRoute = AppCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AppRoute,
} as any)
const AppSellerIndexRoute = AppSellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSellerRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketIndexRoute = AppMarketIndexRouteImport.update({
  id: '/market/',
  path: '/market/',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnIndexRoute = AppLearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => AppRoute,
} as any)
const AppExpertsIndexRoute = AppExpertsIndexRouteImport.update({
  id: '/experts/',
  path: '/experts/',
  getParentRoute: () => AppRoute,
} as any)
const AppDetectIndexRoute = AppDetectIndexRouteImport.update({
  id: '/detect/',
  path: '/detect/',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultationsIndexRoute = AppConsultationsIndexRouteImport.update({
  id: '/consultations/',
  path: '/consultations/',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityIndexRoute = AppCommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => AppRoute,
} as any)
const AppSellerProductsRoute = AppSellerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppSellerRoute,
} as any)
const AppSellerOrdersRoute = AppSellerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppSellerRoute,
} as any)
const AppPlantsIdRoute = AppPlantsIdRouteImport.update({
  id: '/plants/$id',
  path: '/plants/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnSlugRoute = AppLearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppExpertsIdRoute = AppExpertsIdRouteImport.update({
  id: '/experts/$id',
  path: '/experts/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDetectHistoryRoute = AppDetectHistoryRouteImport.update({
  id: '/detect/history',
  path: '/detect/history',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketProductIdRoute = AppMarketProductIdRouteImport.update({
  id: '/market/product/$id',
  path: '/market/product/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDetectResultIdRoute = AppDetectResultIdRouteImport.update({
  id: '/detect/result/$id',
  path: '/detect/result/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultationsIdChatRoute = AppConsultationsIdChatRouteImport.update({
  id: '/consultations/$id/chat',
  path: '/consultations/$id/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityPostIdRoute = AppCommunityPostIdRouteImport.update({
  id: '/community/post/$id',
  path: '/community/post/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/cart': typeof AppCartRoute
  '/checkout': typeof AppCheckoutRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/reminders': typeof AppRemindersRoute
  '/seller': typeof AppSellerRouteWithChildren
  '/subscription': typeof AppSubscriptionRoute
  '/support': typeof AppSupportRoute
  '/detect/history': typeof AppDetectHistoryRoute
  '/experts/$id': typeof AppExpertsIdRoute
  '/learn/$slug': typeof AppLearnSlugRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/plants/$id': typeof AppPlantsIdRoute
  '/seller/orders': typeof AppSellerOrdersRoute
  '/seller/products': typeof AppSellerProductsRoute
  '/community/': typeof AppCommunityIndexRoute
  '/consultations/': typeof AppConsultationsIndexRoute
  '/detect/': typeof AppDetectIndexRoute
  '/experts/': typeof AppExpertsIndexRoute
  '/learn/': typeof AppLearnIndexRoute
  '/market/': typeof AppMarketIndexRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/seller/': typeof AppSellerIndexRoute
  '/community/post/$id': typeof AppCommunityPostIdRoute
  '/consultations/$id/chat': typeof AppConsultationsIdChatRoute
  '/detect/result/$id': typeof AppDetectResultIdRoute
  '/market/product/$id': typeof AppMarketProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/cart': typeof AppCartRoute
  '/checkout': typeof AppCheckoutRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/reminders': typeof AppRemindersRoute
  '/subscription': typeof AppSubscriptionRoute
  '/support': typeof AppSupportRoute
  '/detect/history': typeof AppDetectHistoryRoute
  '/experts/$id': typeof AppExpertsIdRoute
  '/learn/$slug': typeof AppLearnSlugRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/plants/$id': typeof AppPlantsIdRoute
  '/seller/orders': typeof AppSellerOrdersRoute
  '/seller/products': typeof AppSellerProductsRoute
  '/community': typeof AppCommunityIndexRoute
  '/consultations': typeof AppConsultationsIndexRoute
  '/detect': typeof AppDetectIndexRoute
  '/experts': typeof AppExpertsIndexRoute
  '/learn': typeof AppLearnIndexRoute
  '/market': typeof AppMarketIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/seller': typeof AppSellerIndexRoute
  '/community/post/$id': typeof AppCommunityPostIdRoute
  '/consultations/$id/chat': typeof AppConsultationsIdChatRoute
  '/detect/result/$id': typeof AppDetectResultIdRoute
  '/market/product/$id': typeof AppMarketProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/cart': typeof AppCartRoute
  '/_app/checkout': typeof AppCheckoutRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reminders': typeof AppRemindersRoute
  '/_app/seller': typeof AppSellerRouteWithChildren
  '/_app/subscription': typeof AppSubscriptionRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/detect/history': typeof AppDetectHistoryRoute
  '/_app/experts/$id': typeof AppExpertsIdRoute
  '/_app/learn/$slug': typeof AppLearnSlugRoute
  '/_app/orders/$id': typeof AppOrdersIdRoute
  '/_app/plants/$id': typeof AppPlantsIdRoute
  '/_app/seller/orders': typeof AppSellerOrdersRoute
  '/_app/seller/products': typeof AppSellerProductsRoute
  '/_app/community/': typeof AppCommunityIndexRoute
  '/_app/consultations/': typeof AppConsultationsIndexRoute
  '/_app/detect/': typeof AppDetectIndexRoute
  '/_app/experts/': typeof AppExpertsIndexRoute
  '/_app/learn/': typeof AppLearnIndexRoute
  '/_app/market/': typeof AppMarketIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/seller/': typeof AppSellerIndexRoute
  '/_app/community/post/$id': typeof AppCommunityPostIdRoute
  '/_app/consultations/$id/chat': typeof AppConsultationsIdChatRoute
  '/_app/detect/result/$id': typeof AppDetectResultIdRoute
  '/_app/market/product/$id': typeof AppMarketProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/reminders'
    | '/seller'
    | '/subscription'
    | '/support'
    | '/detect/history'
    | '/experts/$id'
    | '/learn/$slug'
    | '/orders/$id'
    | '/plants/$id'
    | '/seller/orders'
    | '/seller/products'
    | '/community/'
    | '/consultations/'
    | '/detect/'
    | '/experts/'
    | '/learn/'
    | '/market/'
    | '/orders/'
    | '/seller/'
    | '/community/post/$id'
    | '/consultations/$id/chat'
    | '/detect/result/$id'
    | '/market/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/reminders'
    | '/subscription'
    | '/support'
    | '/detect/history'
    | '/experts/$id'
    | '/learn/$slug'
    | '/orders/$id'
    | '/plants/$id'
    | '/seller/orders'
    | '/seller/products'
    | '/community'
    | '/consultations'
    | '/detect'
    | '/experts'
    | '/learn'
    | '/market'
    | '/orders'
    | '/seller'
    | '/community/post/$id'
    | '/consultations/$id/chat'
    | '/detect/result/$id'
    | '/market/product/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/_app/cart'
    | '/_app/checkout'
    | '/_app/dashboard'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/reminders'
    | '/_app/seller'
    | '/_app/subscription'
    | '/_app/support'
    | '/_app/detect/history'
    | '/_app/experts/$id'
    | '/_app/learn/$slug'
    | '/_app/orders/$id'
    | '/_app/plants/$id'
    | '/_app/seller/orders'
    | '/_app/seller/products'
    | '/_app/community/'
    | '/_app/consultations/'
    | '/_app/detect/'
    | '/_app/experts/'
    | '/_app/learn/'
    | '/_app/market/'
    | '/_app/orders/'
    | '/_app/seller/'
    | '/_app/community/post/$id'
    | '/_app/consultations/$id/chat'
    | '/_app/detect/result/$id'
    | '/_app/market/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscription': {
      id: '/_app/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seller': {
      id: '/_app/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof AppSellerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reminders': {
      id: '/_app/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AppRemindersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkout': {
      id: '/_app/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cart': {
      id: '/_app/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AppCartRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seller/': {
      id: '/_app/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof AppSellerIndexRouteImport
      parentRoute: typeof AppSellerRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/market/': {
      id: '/_app/market/'
      path: '/market'
      fullPath: '/market/'
      preLoaderRoute: typeof AppMarketIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learn/': {
      id: '/_app/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof AppLearnIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/experts/': {
      id: '/_app/experts/'
      path: '/experts'
      fullPath: '/experts/'
      preLoaderRoute: typeof AppExpertsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/detect/': {
      id: '/_app/detect/'
      path: '/detect'
      fullPath: '/detect/'
      preLoaderRoute: typeof AppDetectIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consultations/': {
      id: '/_app/consultations/'
      path: '/consultations'
      fullPath: '/consultations/'
      preLoaderRoute: typeof AppConsultationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community/': {
      id: '/_app/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof AppCommunityIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seller/products': {
      id: '/_app/seller/products'
      path: '/products'
      fullPath: '/seller/products'
      preLoaderRoute: typeof AppSellerProductsRouteImport
      parentRoute: typeof AppSellerRoute
    }
    '/_app/seller/orders': {
      id: '/_app/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof AppSellerOrdersRouteImport
      parentRoute: typeof AppSellerRoute
    }
    '/_app/plants/$id': {
      id: '/_app/plants/$id'
      path: '/plants/$id'
      fullPath: '/plants/$id'
      preLoaderRoute: typeof AppPlantsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$id': {
      id: '/_app/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learn/$slug': {
      id: '/_app/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof AppLearnSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/experts/$id': {
      id: '/_app/experts/$id'
      path: '/experts/$id'
      fullPath: '/experts/$id'
      preLoaderRoute: typeof AppExpertsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/detect/history': {
      id: '/_app/detect/history'
      path: '/detect/history'
      fullPath: '/detect/history'
      preLoaderRoute: typeof AppDetectHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/market/product/$id': {
      id: '/_app/market/product/$id'
      path: '/market/product/$id'
      fullPath: '/market/product/$id'
      preLoaderRoute: typeof AppMarketProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/detect/result/$id': {
      id: '/_app/detect/result/$id'
      path: '/detect/result/$id'
      fullPath: '/detect/result/$id'
      preLoaderRoute: typeof AppDetectResultIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consultations/$id/chat': {
      id: '/_app/consultations/$id/chat'
      path: '/consultations/$id/chat'
      fullPath: '/consultations/$id/chat'
      preLoaderRoute: typeof AppConsultationsIdChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community/post/$id': {
      id: '/_app/community/post/$id'
      path: '/community/post/$id'
      fullPath: '/community/post/$id'
      preLoaderRoute: typeof AppCommunityPostIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSellerRouteChildren {
  AppSellerOrdersRoute: typeof AppSellerOrdersRoute
  AppSellerProductsRoute: typeof AppSellerProductsRoute
  AppSellerIndexRoute: typeof AppSellerIndexRoute
}

const AppSellerRouteChildren: AppSellerRouteChildren = {
  AppSellerOrdersRoute: AppSellerOrdersRoute,
  AppSellerProductsRoute: AppSellerProductsRoute,
  AppSellerIndexRoute: AppSellerIndexRoute,
}

const AppSellerRouteWithChildren = AppSellerRoute._addFileChildren(
  AppSellerRouteChildren,
)

interface AppRouteChildren {
  AppCartRoute: typeof AppCartRoute
  AppCheckoutRoute: typeof AppCheckoutRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRemindersRoute: typeof AppRemindersRoute
  AppSellerRoute: typeof AppSellerRouteWithChildren
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppSupportRoute: typeof AppSupportRoute
  AppDetectHistoryRoute: typeof AppDetectHistoryRoute
  AppExpertsIdRoute: typeof AppExpertsIdRoute
  AppLearnSlugRoute: typeof AppLearnSlugRoute
  AppOrdersIdRoute: typeof AppOrdersIdRoute
  AppPlantsIdRoute: typeof AppPlantsIdRoute
  AppCommunityIndexRoute: typeof AppCommunityIndexRoute
  AppConsultationsIndexRoute: typeof AppConsultationsIndexRoute
  AppDetectIndexRoute: typeof AppDetectIndexRoute
  AppExpertsIndexRoute: typeof AppExpertsIndexRoute
  AppLearnIndexRoute: typeof AppLearnIndexRoute
  AppMarketIndexRoute: typeof AppMarketIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppCommunityPostIdRoute: typeof AppCommunityPostIdRoute
  AppConsultationsIdChatRoute: typeof AppConsultationsIdChatRoute
  AppDetectResultIdRoute: typeof AppDetectResultIdRoute
  AppMarketProductIdRoute: typeof AppMarketProductIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCartRoute: AppCartRoute,
  AppCheckoutRoute: AppCheckoutRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRemindersRoute: AppRemindersRoute,
  AppSellerRoute: AppSellerRouteWithChildren,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppSupportRoute: AppSupportRoute,
  AppDetectHistoryRoute: AppDetectHistoryRoute,
  AppExpertsIdRoute: AppExpertsIdRoute,
  AppLearnSlugRoute: AppLearnSlugRoute,
  AppOrdersIdRoute: AppOrdersIdRoute,
  AppPlantsIdRoute: AppPlantsIdRoute,
  AppCommunityIndexRoute: AppCommunityIndexRoute,
  AppConsultationsIndexRoute: AppConsultationsIndexRoute,
  AppDetectIndexRoute: AppDetectIndexRoute,
  AppExpertsIndexRoute: AppExpertsIndexRoute,
  AppLearnIndexRoute: AppLearnIndexRoute,
  AppMarketIndexRoute: AppMarketIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppCommunityPostIdRoute: AppCommunityPostIdRoute,
  AppConsultationsIdChatRoute: AppConsultationsIdChatRoute,
  AppDetectResultIdRoute: AppDetectResultIdRoute,
  AppMarketProductIdRoute: AppMarketProductIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
